import type { Metadata } from "next"
import { Inter } from "next/font/google"
import NextTopLoader from "nextjs-toploader"
import { Header } from "@/components/Header"
import { ToastContainer } from "react-toastify"

import "react-toastify/dist/ReactToastify.css"
import "@/styles/globals.css"
import "@/styles/dracula.css"
import "@/styles/mdx.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html 
         lang="en"
      >
         <ToastContainer />
         <body className={`${inter.className} dark:bg-dark`}>
            <Header />
            <NextTopLoader />
            {children}
         </body>
      </html>
   )
}
