import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import NextTopLoader from "nextjs-toploader"
import { Header } from "@/components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html 
         lang="en"
      >
         <body className={inter.className}>
            <Header />
            <div data-type="gradient-animation" className="w-full h-1.5 bg-red-400">

            </div>
            <NextTopLoader />
            {children}
         </body>
      </html>
   )
}
